version: "3.3"
services:
  zalo-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./zalo_data:/app/data
    environment:
      - PORT=${PORT}
      - MESSAGE_WEBHOOK_URL=${MESSAGE_WEBHOOK_URL}
      - GROUP_EVENT_WEBHOOK_URL=${GROUP_EVENT_WEBHOOK_URL}
      - REACTION_WEBHOOK_URL=${REACTION_WEBHOOK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - API_KEY=${API_KEY}
    restart: always
    working_dir: /app 